[package]
name = "snake"
version = "0.1.0"
authors = ["Marek Pokropiński <marek.pokropinski@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.2.1"
sfml = "0.15.1"
rand = "0.5.5"